### ISSUE TITLE
clash-demo.yaml代码有个小问题

### ISSUE THREAD

**Issue by data7799** [zoyo94/conf#1]
clash-demo.yaml这文件节点各地区测速分组里use: - auto应该改为use: - sub，不然会报错

**Comment by zoyo94** [comment]
对对 是的你说的没问题  是我改错了 
一开始用的auto名字，后来为了整理demo给同步错了。  
高阶版本是没问题。
他两其实一样的只是写的更简洁。

**Comment by zoyo94** [comment]
已修改
